### ISSUE TITLE
Publish With `gha-scala-library-release-workflow`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/pa-football-client#76]
Use the documentation here to start publishing this library with GitHub Actions: https://github.com/guardian/gha-scala-library-release-workflow/blob/main/README.md

@rtyley may be able to help with any problems.

```[tasklist]
### Tasks
- [x] Disable branch protection: https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md#repo-settings
- [x] Create `release.yml` workflow: https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md#github-workflow
- [x] Make an equivalent PR to this: https://github.com/guardian/github-secret-access/pull/24
- [x] Do a release to make sure it all works!
```

https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md#recommended-sbt-settings

```[tasklist]
### SBT Changes
- [x] Add `sbt-version-policy` plugin and remove `sbt-pgp` plugin: https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md#recommended-sbt-plugins https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md#unnecessary-sbt-plugins
- [x] Specify license in newer way, `licenses := Seq(License.Apache2)`
- [x] Add `-release:11` to `scalacOptions`
- [x] Update `releaseProcess` to be just this: `checkSnapshotDependencies, inquireVersions, runClean, runTest, setReleaseVersion, commitReleaseVersion, tagRelease, setNextVersion, commitNextVersion`
- [x] Set `releaseVersion := fromAggregatedAssessedCompatibilityWithLatestRelease().value`
- [x] Delete `homepage`
- [x] Delete `developers`
- [x] Delete `publishTo`
- [x] Delete `scmInfo`
```
